### 1. 登录
POST http://localhost:8080/login
Content-Type: application/json

{
  "account": "G2025002",
  "password": "Admin123"
}

> {%
    client.global.set("adminToken", response.body.data.token);
    console.log("管理员 Token 已存储：" + client.global.get("adminToken"));
%}

###2. 查看管理员个人信息
GET http://localhost:8080/api/admin/my-info
Authorization: Bearer {{adminToken}}

###3. 管理员修改密码
PUT http://localhost:8080/api/admin/update-password
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "oldPassword": "Admin123",
  "newPassword": "Aa123456"
}
###4. 管理员上传头像
POST http://localhost:8080/api/admin/avatar
Authorization: Bearer {{adminToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="admin_avatar.png"
Content-Type: image/png

@C:\test.png
----WebKitFormBoundary7MA4YWxkTrZu0gW--


###5. 部门上传头像
POST http://localhost:8080/api/department/avatar
###
# curl -X POST "http://localhost:8080/api/department/avatar" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiRzIwMjUwMDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjQ2MDYwMzUsImV4cCI6MTc2NDYxMzIzNX0.zZx4Eh_JCU2390erCnKP5pm6Rby163hBX8qbe1egkoY" -F "file=@C:\Users\AK\Pictures\Screenshots\屏幕截图 2025-12-01 224312.png" -F "departmentId=1" -v
POST http://localhost:8080/api/department/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiRzIwMjUwMDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjQ2MDYwMzUsImV4cCI6MTc2NDYxMzIzNX0.zZx4Eh_JCU2390erCnKP5pm6Rby163hBX8qbe1egkoY
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="屏幕截图 2025-12-01 224312.png"

< C:\Users\AK\Pictures\Screenshots\屏幕截图 2025-12-01 224312.png
--WebAppBoundary
Content-Disposition: form-data; name="departmentId"

1
--WebAppBoundary--

###


### 6. 查看部门详情
GET http://localhost:8080/api/department/detail?departmentId=3
Content-Type: application/x-www-form-urlencoded

###6. 编辑部门信息
PUT http://localhost:8080/api/department/update
Content-Type: application/json

{
  "departmentId": 1,
  "department_name": "体育部",
  "description": "负责体育相关专业教学与管理"
}


###查看当前部门关注人数
GET http://localhost:8080/api/department/follow-count?departmentId=1
Authorization: Bearer {{adminToken}}

###查看部门发布活动数
GET http://localhost:8080/api/admin/activities/count?departmentId=2
