###1. 搜索联想接口
GET http://localhost:8080/api/activity/search/suggest?keyword=数学

###2. 搜索结果分页接口
GET http://localhost:8080/api/activity/search?keyword=竞赛 & pageNum=1&pageSize=10

###3. 活动详情接口
GET http://localhost:8080/api/activity/detail/6


###1. 搜索联想接口
GET http://localhost:8080/api/department/search/suggest?keyword=法

###2. 搜索结果分页接口
GET http://localhost:8080/api/department/search?keyword=计算 & pageNum=1&pageSize=10

###3. 活动详情接口
GET http://localhost:8080/api/department/detail/3

###
GET http://localhost:8080/api/admin/activity/export/2
Authorization: Bearer {{adminToken}}
Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet