###1. 搜索联想接口
GET http://localhost:8080/api/activity/search/suggest?keyword=数学

###2. 搜索结果分页接口
GET http://localhost:8080/api/activity/search?keyword=竞赛 & pageNum=1&pageSize=10

###3. 活动详情接口
GET http://localhost:8080/api/activity/detail/1