### 1. 用户注册
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "userName": "林一",
  "password":"123456aA",
  "confirmPassword": "123456aA",
  "college":"FOREIGN_LANGUAGE",
  "studentId": "202300210",
  "grade": "GRADE_2025",
  "phone": "13800138005"
}


### 2. 用户登录
POST http://localhost:8080/login
Content-Type: application/json

{
  "account": "202200101",
  "password": "Aa202200101"
}
> {%
    client.global.set("userToken", response.body.data.token);
%}

### 3. 查看用户信息
GET http://localhost:8080/api/user/info
Authorization: Bearer {{userToken}}

### 4. 编辑信息
PUT http://localhost:8080/api/user/update-info
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "phone": "18800139000"
}


### 5. 上传用户头像（文件上传）用curl测试
curl -X POST "http://localhost:8080/api/user/avatar" ^
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..." ^
-F "file=@C:\Users\张三\Pictures\my-avatar.jpg" ^
-v


###6. 查看用户报名过的活动
GET http://localhost:8080/api/user/my-registrations
Authorization: Bearer {{userToken}}

###7.修改密码
PUT http://localhost:8080/api/user/password
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "oldPassword": "Aa1223456",
  "newPassword": "Aa123456"

}

###8. 查看我关注的部门
GET http://localhost:8080/api/user/favorites/departments
Content-Type: application/json
Authorization: Bearer {{userToken}}



###9.查看我收藏的活动
GET http://localhost:8080/api/user/favorites/activities
Content-Type: application/json
Authorization: Bearer {{userToken}}

### 查看报名活动数、收藏活动数和关注部门数
GET http://localhost:8080/api/user/stats
Content-Type: application/json
Authorization: Bearer {{userToken}}